import type { AgencyIncident, AgencyStatus, CrewSummary, Priority } from "./types";

export const CREWS: CrewSummary[] = [
  { id: "c1", name: "Asfalterska ekipa A", vehicle: "Iveco Daily 4x4", members: 4, available: true },
  { id: "c2", name: "Asfalterska ekipa B", vehicle: "MAN TGM", members: 5, available: false },
  { id: "c3", name: "Hitna intervencija", vehicle: "Land Rover Defender", members: 3, available: true },
  { id: "c4", name: "Signalizacija", vehicle: "Renault Master", members: 2, available: true },
  { id: "c5", name: "Zimska služba 1", vehicle: "Mercedes Unimog", members: 3, available: false },
  { id: "c6", name: "Ekipa za održavanje", vehicle: "VW Crafter", members: 3, available: true },
];

export const PRIORITY_LABEL: Record<Priority, string> = {
  urgent: "Hitno",
  high: "Visok",
  normal: "Normalan",
  low: "Nizak",
};

export const STATUS_LABEL: Record<AgencyStatus, string> = {
  new: "Nova",
  triaged: "U triaži",
  in_progress: "U toku",
  resolved: "Rešeno",
  dismissed: "Odbačeno",
};

export const AGENCY_INCIDENTS: AgencyIncident[] = [
  {
    id: "i1",
    type: "pothole",
    priority: "urgent",
    status: "new",
    lng: 20.5158,
    lat: 43.1361,
    address: "Stevana Nemanje 12",
    note: "Duboka rupa pored pešačkog prelaza, više vozila je već oštećeno.",
    photo: "https://picsum.photos/seed/incident-i1/640/360",
    submittedAt: "pre 12 min",
    minsAgo: 12,
    reporter: { name: "Marko Jovanović", initials: "MJ", trust: "verified" },
    duplicates: 3,
  },
  {
    id: "i2",
    type: "sign",
    priority: "high",
    status: "triaged",
    lng: 20.5197,
    lat: 43.1332,
    address: "Trg slobode 3",
    note: 'Znak „Stop" oboren u udesu, raskrsnica nije obeležena.',
    photo: "https://picsum.photos/seed/incident-i2/640/360",
    submittedAt: "pre 58 min",
    minsAgo: 58,
    reporter: { name: "Ana Petrović", initials: "AP", trust: "regular" },
  },
  {
    id: "i3",
    type: "ice",
    priority: "urgent",
    status: "in_progress",
    lng: 20.5068,
    lat: 43.1408,
    address: "Most preko Raške — pristup",
    note: "Poledica, vozila proklizavaju. Hitno potrebna so.",
    photo: "https://picsum.photos/seed/incident-i3/640/360",
    submittedAt: "pre 34 min",
    minsAgo: 34,
    reporter: { name: "Gradske službe", initials: "GS", trust: "verified" },
    assignedCrew: CREWS[4],
    workOrderId: "WO-1042",
  },
  {
    id: "i4",
    type: "debris",
    priority: "normal",
    status: "new",
    lng: 20.5066,
    lat: 43.1428,
    address: "Stara čaršija 4",
    note: "Granje na kolovozu nakon vetra, leva traka neprohodna.",
    photo: "https://picsum.photos/seed/incident-i4/640/360",
    submittedAt: "pre 18 min",
    minsAgo: 18,
    reporter: { name: "Anonimni prijavilac", initials: "?", trust: "anonymous" },
  },
  {
    id: "i5",
    type: "light",
    priority: "low",
    status: "triaged",
    lng: 20.5108,
    lat: 43.1379,
    address: "Bulevar 12. februar 22",
    note: "Ulična rasveta van funkcije već 2 dana.",
    photo: null,
    submittedAt: "pre 3 sata",
    minsAgo: 220,
    reporter: { name: "Ivan Vujović", initials: "IV", trust: "regular" },
  },
  {
    id: "i6",
    type: "flood",
    priority: "high",
    status: "in_progress",
    lng: 20.4992,
    lat: 43.1318,
    address: "Hadžetska 17",
    note: "Manje klizište nakon kiše, jedna traka sužena.",
    photo: "https://picsum.photos/seed/incident-i6/640/360",
    submittedAt: "pre 1 sat",
    minsAgo: 95,
    reporter: { name: "Dušan Milić", initials: "DM", trust: "verified" },
    assignedCrew: CREWS[2],
    workOrderId: "WO-1041",
  },
  {
    id: "i7",
    type: "pothole",
    priority: "high",
    status: "new",
    lng: 20.5142,
    lat: 43.1454,
    address: "Postenje — autobuska linija 5",
    note: "Velika rupa, direktno na liniji autobusa, neophodno hitno krpljenje.",
    photo: "https://picsum.photos/seed/incident-i7/640/360",
    submittedAt: "pre 3 min",
    minsAgo: 3,
    reporter: { name: "Marija Todorović", initials: "MT", trust: "verified" },
    duplicates: 2,
  },
  {
    id: "i8",
    type: "debris",
    priority: "normal",
    status: "resolved",
    lng: 20.5054,
    lat: 43.1248,
    address: "Obilaznica — izlaz Tutin",
    note: "Guma u desnoj traci, sklonjena.",
    photo: "https://picsum.photos/seed/incident-i8/640/360",
    submittedAt: "juče",
    minsAgo: 1300,
    reporter: { name: "Nemanja Vasić", initials: "NV", trust: "regular" },
    assignedCrew: CREWS[5],
    workOrderId: "WO-1037",
  },
  {
    id: "i9",
    type: "pothole",
    priority: "low",
    status: "dismissed",
    lng: 20.5012,
    lat: 43.1342,
    address: "Hadžetska bb",
    note: "Manja rupa, već zakrpljena prošle nedelje.",
    photo: null,
    submittedAt: "pre 2 dana",
    minsAgo: 2880,
    reporter: { name: "Anonimni prijavilac", initials: "?", trust: "anonymous" },
  },
  {
    id: "i10",
    type: "sign",
    priority: "normal",
    status: "new",
    lng: 20.5302,
    lat: 43.1289,
    address: "Selakovac — krivina kod škole",
    note: "Nedostaje znak za ograničenje brzine 30.",
    photo: "https://picsum.photos/seed/incident-i10/640/360",
    submittedAt: "pre 95 min",
    minsAgo: 95,
    reporter: { name: "Jovana Stanković", initials: "JS", trust: "verified" },
  },
  {
    id: "i11",
    type: "flood",
    priority: "normal",
    status: "triaged",
    lng: 20.5189,
    lat: 43.1471,
    address: "Postenje — slivnik kod parka",
    note: "Nakupljanje vode posle kiše, slivnik začepljen.",
    photo: "https://picsum.photos/seed/incident-i11/640/360",
    submittedAt: "pre 2 sata",
    minsAgo: 130,
    reporter: { name: "Komšije iz parka", initials: "KP", trust: "regular" },
  },
  {
    id: "i12",
    type: "pothole",
    priority: "normal",
    status: "in_progress",
    lng: 20.5246,
    lat: 43.1391,
    address: "Selakovac — krivina",
    note: "Više udarnih rupa u nizu.",
    photo: "https://picsum.photos/seed/incident-i12/640/360",
    submittedAt: "jutros",
    minsAgo: 280,
    reporter: { name: "Branko Aleksić", initials: "BA", trust: "regular" },
    assignedCrew: CREWS[0],
    workOrderId: "WO-1040",
  },
];
