import type {
  AssetVehicle,
  Depot,
  EquipmentItem,
  Worker,
  WorkerRole,
  Shift,
  WorkerStatus,
  EquipmentCategory,
  StockLevel,
} from "./types";

export const ROLE_LABEL: Record<WorkerRole, string> = {
  asphalt_worker: "Asfalter",
  driver: "Vozač",
  electrician: "Električar",
  mechanic: "Mehaničar",
  inspector: "Inspektor",
  dispatcher: "Dispečer",
  signs_specialist: "Specijalista za signalizaciju",
  general: "Pomoćni radnik",
};

export const SHIFT_LABEL: Record<Shift, string> = {
  morning: "Jutarnja",
  afternoon: "Popodnevna",
  night: "Noćna",
  on_call: "Na poziv",
};

export const STATUS_LABEL: Record<WorkerStatus, string> = {
  active: "Aktivan",
  on_leave: "Odmor",
  training: "Obuka",
  sick: "Bolovanje",
  field: "Na terenu",
};

export const STATUS_TONE: Record<WorkerStatus, string> = {
  active: "bg-signal-green/15 text-signal-green ring-1 ring-signal-green/30",
  field: "bg-signal-ice/15 text-[#0F7AB3] ring-1 ring-signal-ice/40",
  on_leave: "bg-ink-100 text-ink-500 ring-1 ring-ink-200",
  training: "bg-signal-amber/15 text-signal-amber ring-1 ring-signal-amber/30",
  sick: "bg-signal-red/15 text-signal-red ring-1 ring-signal-red/30",
};

export const CATEGORY_LABEL: Record<EquipmentCategory, string> = {
  consumable: "Materijali za potrošnju",
  traffic_gear: "Saobraćajna oprema",
  machinery: "Mašine i uređaji",
  small_tools: "Sitan inventar",
  ppe: "Lična zaštitna oprema",
};

export const STOCK_TONE: Record<StockLevel, string> = {
  ok: "text-signal-green",
  low: "text-signal-amber",
  critical: "text-signal-red",
  overstock: "text-[#0F7AB3]",
};

export const DEPOTS: Depot[] = [
  {
    id: "d1",
    name: "Glavna baza · Putevi NP",
    address: "Industrijska zona, Novi Pazar",
    lng: 20.4945,
    lat: 43.1418,
  },
  {
    id: "d2",
    name: "Magacin Hadžet",
    address: "Hadžetska bb, Novi Pazar",
    lng: 20.5012,
    lat: 43.1295,
  },
  {
    id: "d3",
    name: "Depo signalizacije",
    address: "Vihbe Kolašinca, Novi Pazar",
    lng: 20.5185,
    lat: 43.1382,
  },
];

export const ASSET_VEHICLES: AssetVehicle[] = [
  {
    id: "av1",
    fleetId: "v1",
    plate: "NP 042-AB",
    callSign: "AsfaltA-1",
    kind: "asphalt_truck",
    brand: "Iveco",
    model: "Daily 4x4 70C18",
    year: 2021,
    acquiredOn: "2021-04-12",
    acquisitionCost: 64500,
    bookValue: 41200,
    totalKm: 84320,
    avgConsumption: 18.4,
    yearlyCost: 7240,
    registrationUntil: "2026-08-14",
    technicalUntil: "2026-08-14",
    status: "on_site",
    assignedCrew: "Asfalterska ekipa A",
    driver: "Slobodan M.",
  },
  {
    id: "av2",
    fleetId: "v3",
    plate: "NP 308-EF",
    callSign: "Zima-1",
    kind: "snow_plow",
    brand: "Mercedes-Benz",
    model: "Unimog U400",
    year: 2018,
    acquiredOn: "2018-11-03",
    acquisitionCost: 92000,
    bookValue: 38400,
    totalKm: 142500,
    avgConsumption: 26.8,
    yearlyCost: 12480,
    registrationUntil: "2026-11-22",
    technicalUntil: "2026-05-30",
    status: "en_route",
    assignedCrew: "Zimska služba 1",
    driver: "Đorđe S.",
    alerts: ["Tehnički pregled za 28 dana"],
  },
  {
    id: "av3",
    fleetId: "v2",
    plate: "NP 113-CD",
    callSign: "Hitna-1",
    kind: "emergency",
    brand: "Land Rover",
    model: "Defender 130",
    year: 2022,
    acquiredOn: "2022-09-21",
    acquisitionCost: 71200,
    bookValue: 56800,
    totalKm: 38940,
    avgConsumption: 12.6,
    yearlyCost: 5180,
    registrationUntil: "2027-01-10",
    technicalUntil: "2027-01-10",
    status: "on_site",
    assignedCrew: "Hitna intervencija",
    driver: "Vladan K.",
  },
  {
    id: "av4",
    fleetId: "v5",
    plate: "NP 075-IJ",
    callSign: "AsfaltB-1",
    kind: "asphalt_truck",
    brand: "MAN",
    model: "TGM 18.290",
    year: 2017,
    acquiredOn: "2017-07-04",
    acquisitionCost: 78500,
    bookValue: 24300,
    totalKm: 218400,
    avgConsumption: 28.2,
    yearlyCost: 9320,
    registrationUntil: "2026-06-18",
    technicalUntil: "2026-06-18",
    status: "returning",
    assignedCrew: "Asfalterska ekipa B",
    driver: "Mirko P.",
    alerts: ["Servis: za 1.500 km"],
  },
  {
    id: "av5",
    fleetId: "v4",
    plate: "NP 220-GH",
    callSign: "Sig-1",
    kind: "service_van",
    brand: "Renault",
    model: "Master L3H2",
    year: 2020,
    acquiredOn: "2020-02-19",
    acquisitionCost: 38400,
    bookValue: 22100,
    totalKm: 96280,
    avgConsumption: 9.4,
    yearlyCost: 3120,
    registrationUntil: "2026-12-04",
    technicalUntil: "2026-12-04",
    status: "idle",
    assignedCrew: "Signalizacija",
    driver: "Jelena R.",
  },
  {
    id: "av6",
    fleetId: "v6",
    plate: "NP 154-KL",
    callSign: "Servis-2",
    kind: "service_van",
    brand: "Volkswagen",
    model: "Crafter 35",
    year: 2019,
    acquiredOn: "2019-05-26",
    acquisitionCost: 41200,
    bookValue: 21600,
    totalKm: 124850,
    avgConsumption: 10.8,
    yearlyCost: 3760,
    registrationUntil: "2026-10-11",
    technicalUntil: "2026-10-11",
    status: "idle",
    assignedCrew: "Ekipa za održavanje",
    driver: "Dragan T.",
  },
  {
    id: "av7",
    fleetId: "v7",
    plate: "NP 401-MN",
    callSign: "Patrola-1",
    kind: "patrol",
    brand: "Dacia",
    model: "Duster 4x4",
    year: 2023,
    acquiredOn: "2023-03-08",
    acquisitionCost: 22800,
    bookValue: 19400,
    totalKm: 24380,
    avgConsumption: 7.6,
    yearlyCost: 1820,
    registrationUntil: "2027-04-02",
    technicalUntil: "2027-04-02",
    status: "en_route",
    assignedCrew: "Putna patrola",
    driver: "Marko D.",
  },
  {
    id: "av8",
    fleetId: "v8",
    plate: "NP 268-OP",
    callSign: "Kiper-1",
    kind: "tipper",
    brand: "FAP",
    model: "1418 6x4",
    year: 2015,
    acquiredOn: "2015-08-30",
    acquisitionCost: 56000,
    bookValue: 11200,
    totalKm: 312600,
    avgConsumption: 32.4,
    yearlyCost: 8640,
    registrationUntil: "2026-09-25",
    technicalUntil: "2026-09-25",
    status: "off_duty",
    assignedCrew: "Transport",
    driver: "Stefan B.",
  },
  {
    id: "av9",
    plate: "NP 112-QR",
    callSign: "Kiper-2",
    kind: "tipper",
    brand: "MAN",
    model: "TGS 33.480",
    year: 2020,
    acquiredOn: "2020-10-15",
    acquisitionCost: 88200,
    bookValue: 51400,
    totalKm: 168400,
    avgConsumption: 30.1,
    yearlyCost: 7280,
    registrationUntil: "2026-11-08",
    technicalUntil: "2026-11-08",
    status: "service",
    assignedCrew: "Transport",
    driver: "—",
    alerts: ["U servisu: zamena spojnice"],
  },
  {
    id: "av10",
    plate: "NP 089-ST",
    callSign: "Pres-1",
    kind: "service_van",
    brand: "Ford",
    model: "Transit Custom",
    year: 2014,
    acquiredOn: "2014-06-22",
    acquisitionCost: 18400,
    bookValue: 0,
    totalKm: 386200,
    avgConsumption: 11.2,
    yearlyCost: 4180,
    registrationUntil: "—",
    technicalUntil: "—",
    status: "decommissioned",
    notes: "Predloženo otpisivanje",
  },
];

export const WORKERS: Worker[] = [
  {
    id: "w1",
    name: "Slobodan Marković",
    initials: "SM",
    role: "driver",
    crewId: "c1",
    crewName: "Asfalterska ekipa A",
    shift: "morning",
    status: "field",
    experienceYears: 14,
    hiredOn: "2010-04-18",
    phone: "+381 65 412 8810",
    certifications: [
      { code: "CPC", label: "CPC vozača", validUntil: "2027-09-12" },
      { code: "C", label: "Kategorija C", validUntil: "2028-04-10" },
    ],
    lng: 20.5246,
    lat: 43.1391,
  },
  {
    id: "w2",
    name: "Đorđe Stojanović",
    initials: "ĐS",
    role: "driver",
    crewId: "c5",
    crewName: "Zimska služba 1",
    shift: "night",
    status: "field",
    experienceYears: 9,
    hiredOn: "2015-11-02",
    phone: "+381 64 220 5512",
    certifications: [
      { code: "CPC", label: "CPC vozača", validUntil: "2026-11-30" },
      { code: "C+E", label: "Kategorija C+E", validUntil: "2027-08-22" },
    ],
    lng: 20.5135,
    lat: 43.1395,
  },
  {
    id: "w3",
    name: "Vladan Kovačević",
    initials: "VK",
    role: "general",
    crewId: "c3",
    crewName: "Hitna intervencija",
    shift: "on_call",
    status: "field",
    experienceYears: 11,
    hiredOn: "2013-06-12",
    phone: "+381 63 110 4280",
    certifications: [
      { code: "ZNR", label: "Sigurnost na radu II", validUntil: "2027-02-14" },
      { code: "B", label: "Kategorija B", validUntil: "2030-05-04" },
    ],
    lng: 20.4992,
    lat: 43.1318,
  },
  {
    id: "w4",
    name: "Jelena Rakić",
    initials: "JR",
    role: "signs_specialist",
    crewId: "c4",
    crewName: "Signalizacija",
    shift: "morning",
    status: "active",
    experienceYears: 7,
    hiredOn: "2017-09-05",
    phone: "+381 65 884 0142",
    certifications: [
      { code: "ATEST-S", label: "Atest postavljanja saobraćajne signalizacije", validUntil: "2026-12-09" },
    ],
    lng: 20.5121,
    lat: 43.1352,
  },
  {
    id: "w5",
    name: "Marko Dimitrijević",
    initials: "MD",
    role: "inspector",
    crewName: "Putna patrola",
    shift: "morning",
    status: "field",
    experienceYears: 16,
    hiredOn: "2008-03-21",
    phone: "+381 64 311 4080",
    certifications: [
      { code: "ATEST-I", label: "Atest inspekcije puteva", validUntil: "2027-05-30" },
      { code: "B", label: "Kategorija B", validUntil: "2028-12-01" },
    ],
    lng: 20.5055,
    lat: 43.1442,
  },
  {
    id: "w6",
    name: "Mirko Pavlović",
    initials: "MP",
    role: "asphalt_worker",
    crewId: "c2",
    crewName: "Asfalterska ekipa B",
    shift: "morning",
    status: "field",
    experienceYears: 19,
    hiredOn: "2005-07-08",
    phone: "+381 63 405 2208",
    certifications: [
      { code: "C", label: "Kategorija C", validUntil: "2026-10-15" },
    ],
    lng: 20.5074,
    lat: 43.1267,
  },
  {
    id: "w7",
    name: "Ana Petrović",
    initials: "AP",
    role: "asphalt_worker",
    crewId: "c1",
    crewName: "Asfalterska ekipa A",
    shift: "morning",
    status: "field",
    experienceYears: 6,
    hiredOn: "2018-04-30",
    phone: "+381 65 712 0145",
    certifications: [
      { code: "ZNR", label: "Sigurnost na radu I", validUntil: "2027-08-08" },
    ],
    lng: 20.5246,
    lat: 43.1391,
  },
  {
    id: "w8",
    name: "Dragan Todorović",
    initials: "DT",
    role: "general",
    crewId: "c6",
    crewName: "Ekipa za održavanje",
    shift: "afternoon",
    status: "active",
    experienceYears: 12,
    hiredOn: "2012-10-14",
    phone: "+381 64 880 1192",
    certifications: [
      { code: "B", label: "Kategorija B", validUntil: "2027-11-21" },
    ],
    lng: 20.5198,
    lat: 43.1428,
  },
  {
    id: "w9",
    name: "Stefan Bajić",
    initials: "SB",
    role: "driver",
    crewName: "Transport",
    shift: "morning",
    status: "on_leave",
    experienceYears: 4,
    hiredOn: "2020-05-18",
    phone: "+381 65 221 4408",
    certifications: [
      { code: "CPC", label: "CPC vozača", validUntil: "2026-06-30" },
      { code: "C+E", label: "Kategorija C+E", validUntil: "2028-02-12" },
    ],
  },
  {
    id: "w10",
    name: "Aleksandar Pavlović",
    initials: "AP",
    role: "dispatcher",
    crewName: "Centrala",
    shift: "morning",
    status: "active",
    experienceYears: 10,
    hiredOn: "2014-02-04",
    phone: "+381 65 999 1234",
    certifications: [
      { code: "ATEST-D", label: "Sertifikat dispečera", validUntil: "2027-03-18" },
    ],
  },
  {
    id: "w11",
    name: "Marija Todorović",
    initials: "MT",
    role: "dispatcher",
    crewName: "Komunikacije",
    shift: "afternoon",
    status: "active",
    experienceYears: 5,
    hiredOn: "2019-11-12",
    phone: "+381 65 808 2034",
    certifications: [],
  },
  {
    id: "w12",
    name: "Nemanja Ilić",
    initials: "NI",
    role: "electrician",
    crewName: "Elektroservis",
    shift: "morning",
    status: "training",
    experienceYears: 3,
    hiredOn: "2021-08-22",
    phone: "+381 63 144 7720",
    certifications: [
      { code: "ELE", label: "Sertifikat za rad pod naponom", validUntil: "2026-08-28" },
    ],
  },
  {
    id: "w13",
    name: "Branko Aleksić",
    initials: "BA",
    role: "mechanic",
    crewName: "Garaža",
    shift: "morning",
    status: "active",
    experienceYears: 22,
    hiredOn: "2002-09-09",
    phone: "+381 64 504 8800",
    certifications: [
      { code: "MEH", label: "Sertifikat mehaničara", validUntil: "2028-04-15" },
    ],
  },
  {
    id: "w14",
    name: "Ivan Vujović",
    initials: "IV",
    role: "general",
    crewId: "c6",
    crewName: "Ekipa za održavanje",
    shift: "afternoon",
    status: "sick",
    experienceYears: 8,
    hiredOn: "2016-01-29",
    phone: "+381 65 220 1108",
    certifications: [
      { code: "B", label: "Kategorija B", validUntil: "2026-11-30" },
    ],
  },
  {
    id: "w15",
    name: "Jovana Stanković",
    initials: "JS",
    role: "inspector",
    crewName: "Tehnička služba",
    shift: "morning",
    status: "active",
    experienceYears: 9,
    hiredOn: "2015-05-04",
    phone: "+381 64 218 0440",
    certifications: [
      { code: "ATEST-I", label: "Atest inspekcije puteva", validUntil: "2027-09-12" },
      { code: "GIS", label: "Sertifikat GIS analize", validUntil: "2028-03-15" },
    ],
  },
];

export const EQUIPMENT: EquipmentItem[] = [
  // Materials
  { id: "e1", category: "consumable", name: "So za posipanje (NaCl)", unit: "t", qty: 24, threshold: 40, reorderQty: 30, lastDelivery: "pre 11 dana", unitCost: 180, level: "low", depotId: "d1" },
  { id: "e2", category: "consumable", name: "Pesak-so mešavina", unit: "t", qty: 18, threshold: 25, reorderQty: 20, lastDelivery: "pre 6 dana", unitCost: 95, level: "ok", depotId: "d1" },
  { id: "e3", category: "consumable", name: "Hladni asfalt AB-11", unit: "t", qty: 4.2, threshold: 8, reorderQty: 8, lastDelivery: "pre 4 dana", unitCost: 360, level: "low", depotId: "d1" },
  { id: "e4", category: "consumable", name: "Topli asfalt", unit: "t", qty: 1.4, threshold: 4, reorderQty: 6, lastDelivery: "danas 06:30", unitCost: 410, level: "critical", depotId: "d1" },
  { id: "e5", category: "consumable", name: "Bitumenska emulzija", unit: "L", qty: 320, threshold: 500, reorderQty: 400, lastDelivery: "pre 9 dana", unitCost: 4.2, level: "low", depotId: "d1" },
  { id: "e6", category: "consumable", name: "Beton C20/25 (kesa 25kg)", unit: "kom", qty: 84, threshold: 60, lastDelivery: "pre 2 dana", unitCost: 12, level: "ok", depotId: "d2" },

  // Traffic gear
  { id: "e7", category: "traffic_gear", name: "Saobraćajni znaci (B-2 Stop)", unit: "kom", qty: 14, threshold: 8, lastDelivery: "pre 3 nedelje", unitCost: 65, level: "ok", depotId: "d3" },
  { id: "e8", category: "traffic_gear", name: "Saobraćajni znaci (II-30)", unit: "kom", qty: 6, threshold: 10, lastDelivery: "pre 12 dana", unitCost: 58, level: "low", depotId: "d3" },
  { id: "e9", category: "traffic_gear", name: "Stubovi Ø60 × 3000mm", unit: "kom", qty: 22, threshold: 12, lastDelivery: "pre 4 nedelje", unitCost: 38, level: "ok", depotId: "d3" },
  { id: "e10", category: "traffic_gear", name: "Saobraćajni čunjevi 50cm", unit: "kom", qty: 84, threshold: 60, lastDelivery: "pre 8 meseci", unitCost: 14, level: "ok", depotId: "d3" },
  { id: "e11", category: "traffic_gear", name: "Privremene barijere (jersey)", unit: "kom", qty: 32, threshold: 20, unitCost: 240, level: "ok", depotId: "d1" },
  { id: "e12", category: "traffic_gear", name: "Treperajuća svetla A-IV", unit: "kom", qty: 4, threshold: 8, unitCost: 95, level: "critical", depotId: "d3" },

  // Machinery
  { id: "e13", category: "machinery", name: "Krpilica asfalta DURA-PATCHER", unit: "kom", qty: 1, threshold: 1, level: "ok", depotId: "d1", notes: "Servisirana pre 2 nedelje" },
  { id: "e14", category: "machinery", name: "Mašina za horizontalnu signalizaciju", unit: "kom", qty: 1, threshold: 1, level: "ok", depotId: "d3" },
  { id: "e15", category: "machinery", name: "Generator dizel 5kVA", unit: "kom", qty: 3, threshold: 2, level: "ok", depotId: "d1" },
  { id: "e16", category: "machinery", name: "Kompresor PORTAL P-160", unit: "kom", qty: 2, threshold: 2, level: "ok", depotId: "d1" },
  { id: "e17", category: "machinery", name: "Vibro ploča 200kg", unit: "kom", qty: 4, threshold: 3, level: "ok", depotId: "d2" },
  { id: "e18", category: "machinery", name: "LED reflektor 50W", unit: "kom", qty: 2, threshold: 8, lastDelivery: "pre 5 dana", unitCost: 42, level: "critical", depotId: "d3" },

  // Small tools
  { id: "e19", category: "small_tools", name: "Lopate i metle", unit: "kom", qty: 24, threshold: 12, level: "ok", depotId: "d1" },
  { id: "e20", category: "small_tools", name: "Akumulatorska bušilica", unit: "kom", qty: 5, threshold: 4, level: "ok", depotId: "d2" },

  // PPE
  { id: "e21", category: "ppe", name: "Reflexne prsluke (HV)", unit: "kom", qty: 22, threshold: 30, lastDelivery: "pre 1 mesec", unitCost: 18, level: "low", depotId: "d1" },
  { id: "e22", category: "ppe", name: "Zaštitne kacige", unit: "kom", qty: 28, threshold: 24, level: "ok", depotId: "d1" },
  { id: "e23", category: "ppe", name: "Radne rukavice", unit: "par", qty: 96, threshold: 60, level: "ok", depotId: "d1" },
  { id: "e24", category: "ppe", name: "Zaštitne čizme S3", unit: "par", qty: 14, threshold: 18, lastDelivery: "pre 2 meseca", unitCost: 64, level: "low", depotId: "d1" },
];
