import type { FleetVehicle, VehicleKind, VehicleStatus } from "./types";

export const VEHICLE_KIND_LABEL: Record<VehicleKind, string> = {
  asphalt_truck: "Asfaltni kamion",
  patrol: "Patrolno vozilo",
  snow_plow: "Snežni plug",
  service_van: "Servisni kombi",
  emergency: "Hitna intervencija",
  tipper: "Kiper",
};

export const STATUS_LABEL: Record<VehicleStatus, string> = {
  idle: "Slobodno",
  en_route: "Na putu",
  on_site: "Na terenu",
  returning: "Povratak",
  off_duty: "Van smene",
};

export const STATUS_COLOR: Record<VehicleStatus, string> = {
  idle: "#2BB673",
  en_route: "#FF5A1F",
  on_site: "#0F7AB3",
  returning: "#7C5CFF",
  off_duty: "#9B9FAD",
};

export const FLEET: FleetVehicle[] = [
  {
    id: "v1",
    plate: "NP 042-AB",
    callSign: "AsfaltA-1",
    kind: "asphalt_truck",
    crewName: "Asfalterska ekipa A",
    driver: "Slobodan M.",
    status: "on_site",
    lng: 20.5246,
    lat: 43.1391,
    heading: 90,
    speedKmh: 0,
    fuelPct: 64,
    workOrderId: "WO-1040",
    destination: "Selakovac — krivina kod škole",
    etaMins: 0,
    lastPing: "pre 22 sek",
  },
  {
    id: "v2",
    plate: "NP 113-CD",
    callSign: "Hitna-1",
    kind: "emergency",
    crewName: "Hitna intervencija",
    driver: "Vladan K.",
    status: "on_site",
    lng: 20.4992,
    lat: 43.1318,
    heading: 220,
    speedKmh: 0,
    fuelPct: 78,
    workOrderId: "WO-1041",
    destination: "Hadžetska 17 — klizište",
    etaMins: 0,
    lastPing: "pre 14 sek",
  },
  {
    id: "v3",
    plate: "NP 308-EF",
    callSign: "Zima-1",
    kind: "snow_plow",
    crewName: "Zimska služba 1",
    driver: "Đorđe S.",
    status: "en_route",
    lng: 20.5135,
    lat: 43.1395,
    heading: 320,
    speedKmh: 38,
    fuelPct: 51,
    workOrderId: "WO-1042",
    destination: "Most preko Raške",
    etaMins: 6,
    lastPing: "pre 8 sek",
  },
  {
    id: "v4",
    plate: "NP 220-GH",
    callSign: "Sig-1",
    kind: "service_van",
    crewName: "Signalizacija",
    driver: "Jelena R.",
    status: "idle",
    lng: 20.5121,
    lat: 43.1352,
    heading: 0,
    speedKmh: 0,
    fuelPct: 87,
    workOrderId: null,
    destination: null,
    etaMins: null,
    lastPing: "pre 1 min",
  },
  {
    id: "v5",
    plate: "NP 075-IJ",
    callSign: "AsfaltB-1",
    kind: "asphalt_truck",
    crewName: "Asfalterska ekipa B",
    driver: "Mirko P.",
    status: "returning",
    lng: 20.5074,
    lat: 43.1267,
    heading: 30,
    speedKmh: 52,
    fuelPct: 28,
    workOrderId: "WO-1036",
    destination: "Baza — Putevi NP",
    etaMins: 12,
    lastPing: "pre 6 sek",
  },
  {
    id: "v6",
    plate: "NP 154-KL",
    callSign: "Servis-2",
    kind: "service_van",
    crewName: "Ekipa za održavanje",
    driver: "Dragan T.",
    status: "idle",
    lng: 20.5198,
    lat: 43.1428,
    heading: 0,
    speedKmh: 0,
    fuelPct: 71,
    workOrderId: null,
    destination: null,
    etaMins: null,
    lastPing: "pre 2 min",
  },
  {
    id: "v7",
    plate: "NP 401-MN",
    callSign: "Patrola-1",
    kind: "patrol",
    crewName: "Putna patrola",
    driver: "Marko D.",
    status: "en_route",
    lng: 20.5055,
    lat: 43.1442,
    heading: 110,
    speedKmh: 41,
    fuelPct: 63,
    workOrderId: null,
    destination: "Stara čaršija — kontrola",
    etaMins: 4,
    lastPing: "pre 5 sek",
  },
  {
    id: "v8",
    plate: "NP 268-OP",
    callSign: "Kiper-1",
    kind: "tipper",
    crewName: "Transport",
    driver: "Stefan B.",
    status: "off_duty",
    lng: 20.5056,
    lat: 43.1235,
    heading: 0,
    speedKmh: 0,
    fuelPct: 95,
    workOrderId: null,
    destination: "Baza — Putevi NP",
    etaMins: null,
    lastPing: "pre 18 min",
  },
];
