import type { WorkOrder, WorkOrderStatus, WorkType } from "./types";
import { CREWS } from "@/features/incidents/pitch/mockData";

export const STATUS_LABEL: Record<WorkOrderStatus, string> = {
  created: "Kreirano",
  in_progress: "U toku",
  completed: "Završeno",
  blocked: "Blokirano",
};

export const WORK_TYPE_LABEL: Record<WorkType, string> = {
  asphalt_patch: "Krpljenje asfalta",
  sign_replace: "Zamena znaka",
  snow_clearing: "Čišćenje snega",
  drainage: "Čišćenje slivnika",
  lighting: "Servis rasvete",
  debris_removal: "Uklanjanje otpada",
  marking: "Horizontalna signalizacija",
  emergency: "Hitna intervencija",
};

export const WORK_ORDERS: WorkOrder[] = [
  {
    id: "WO-1042",
    incidentId: "i3",
    incidentType: "ice",
    workType: "snow_clearing",
    title: "Posipanje soli — pristup mostu",
    address: "Most preko Raške — pristup",
    status: "in_progress",
    priority: "urgent",
    crew: CREWS[4],
    createdAt: "danas 08:14",
    scheduledFor: "danas 09:00",
    description: "Posipanje soli i pesak-soli mešavine na celom prilazu, fokus na desnu krivinu.",
    photoBefore: "https://picsum.photos/seed/wo1042-before/640/360",
    photoAfter: null,
    materials: [
      { name: "So za posipanje", qty: "240 kg" },
      { name: "Pesak-so mešavina", qty: "180 kg" },
    ],
    cost: 320,
  },
  {
    id: "WO-1041",
    incidentId: "i6",
    incidentType: "flood",
    workType: "drainage",
    title: "Sanacija manjeg klizišta",
    address: "Hadžetska 17",
    status: "in_progress",
    priority: "high",
    crew: CREWS[2],
    createdAt: "danas 06:42",
    scheduledFor: "danas 07:30",
    description: "Uklanjanje obrušenog materijala, postavljanje privremene signalizacije.",
    photoBefore: "https://picsum.photos/seed/wo1041-before/640/360",
    photoAfter: null,
    materials: [{ name: "Privremena signalizacija", qty: "4 znaka" }],
    cost: 480,
  },
  {
    id: "WO-1040",
    incidentId: "i12",
    incidentType: "pothole",
    workType: "asphalt_patch",
    title: "Krpljenje udarnih rupa — Selakovac",
    address: "Selakovac — krivina kod škole",
    status: "in_progress",
    priority: "normal",
    crew: CREWS[0],
    createdAt: "danas 07:10",
    scheduledFor: "danas 09:30",
    description: "Krpljenje 3 udarne rupe u nizu, uklanjanje vode i pripremni rad.",
    photoBefore: "https://picsum.photos/seed/wo1040-before/640/360",
    photoAfter: null,
    materials: [
      { name: "Hladni asfalt", qty: "320 kg" },
      { name: "Bitumenska emulzija", qty: "12 l" },
    ],
    cost: 540,
  },
  {
    id: "WO-1039",
    incidentId: "i2",
    incidentType: "sign",
    workType: "sign_replace",
    title: 'Postavljanje znaka „Stop"',
    address: "Trg slobode 3",
    status: "created",
    priority: "high",
    crew: CREWS[3],
    createdAt: "danas 09:05",
    scheduledFor: "sutra 08:00",
    description: 'Postavljanje novog znaka „Stop" sa stubom i temeljom.',
    photoBefore: "https://picsum.photos/seed/wo1039-before/640/360",
    photoAfter: null,
    materials: [
      { name: "Saobraćajni znak B-2", qty: "1 kom" },
      { name: "Stub Ø60×3000", qty: "1 kom" },
      { name: "Beton C20/25", qty: "0.05 m³" },
    ],
    cost: 210,
  },
  {
    id: "WO-1038",
    incidentId: "i7",
    incidentType: "pothole",
    workType: "asphalt_patch",
    title: "Hitno krpljenje — autobuska ruta",
    address: "Postenje — autobuska linija 5",
    status: "created",
    priority: "high",
    crew: CREWS[0],
    createdAt: "danas 09:18",
    scheduledFor: "sutra 06:30",
    description: "Hitno krpljenje rupe na liniji autobusa, posao mora pre 06:30 ujutru.",
    photoBefore: "https://picsum.photos/seed/wo1038-before/640/360",
    photoAfter: null,
    materials: [{ name: "Topli asfalt", qty: "180 kg" }],
    cost: 290,
  },
  {
    id: "WO-1037",
    incidentId: "i8",
    incidentType: "debris",
    workType: "debris_removal",
    title: "Uklanjanje gume sa kolovoza",
    address: "Obilaznica — izlaz Tutin",
    status: "completed",
    priority: "normal",
    crew: CREWS[5],
    createdAt: "juče 14:20",
    scheduledFor: "juče 15:00",
    completedAt: "juče 15:38",
    durationHours: 0.6,
    description: "Sklanjanje stare gume i provera kolovoza.",
    photoBefore: "https://picsum.photos/seed/wo1037-before/640/360",
    photoAfter: "https://picsum.photos/seed/wo1037-after/640/360",
    materials: [],
    cost: 60,
  },
  {
    id: "WO-1036",
    incidentId: "x1",
    incidentType: "pothole",
    workType: "asphalt_patch",
    title: "Krpljenje rupe — 13. jula",
    address: "Ulica 13. jula 8",
    status: "completed",
    priority: "normal",
    crew: CREWS[1],
    createdAt: "pre 2 dana",
    scheduledFor: "pre 2 dana 09:00",
    completedAt: "pre 2 dana 13:24",
    durationHours: 4.4,
    description: "Frezovanje i polaganje novog sloja asfalta na 14 m².",
    photoBefore: "https://picsum.photos/seed/wo1036-before/640/360",
    photoAfter: "https://picsum.photos/seed/wo1036-after/640/360",
    materials: [
      { name: "Topli asfalt AB-11", qty: "780 kg" },
      { name: "Bitumenska emulzija", qty: "32 l" },
    ],
    cost: 1180,
  },
  {
    id: "WO-1035",
    incidentId: "x2",
    incidentType: "light",
    workType: "lighting",
    title: "Zamena 6 LED reflektora",
    address: "Selakovac — Borisa Kidriča",
    status: "completed",
    priority: "low",
    crew: CREWS[3],
    createdAt: "pre 3 dana",
    scheduledFor: "pre 3 dana 22:00",
    completedAt: "pre 2 dana 03:10",
    durationHours: 5.2,
    description: "Zamena 6 LED reflektora 50W, čišćenje konzola.",
    photoBefore: "https://picsum.photos/seed/wo1035-before/640/360",
    photoAfter: "https://picsum.photos/seed/wo1035-after/640/360",
    materials: [{ name: "LED reflektor 50W", qty: "6 kom" }],
    cost: 720,
  },
];
